// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ResetShareConfig() {
  return window['go']['server']['ShareConfig']['ResetShareConfig']();
}

export function SetShareConfig(arg1, arg2, arg3, arg4) {
  return window['go']['server']['ShareConfig']['SetShareConfig'](arg1, arg2, arg3, arg4);
}

export function SetShareConfigPID(arg1) {
  return window['go']['server']['ShareConfig']['SetShareConfigPID'](arg1);
}

export function UpdateShareConfig(arg1) {
  return window['go']['server']['ShareConfig']['UpdateShareConfig'](arg1);
}
