// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ResetShareConfig():Promise<void>;

export function SetShareConfig(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SetShareConfigPID(arg1:number):Promise<void>;

export function UpdateShareConfig(arg1:string):Promise<void>;
